<?php
function employee_menu() {
  $items['employee/create'] = array(
    'title' => 'Create Employee',
    'page callback' => 'employee_page',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Returns form render array.
 */
function employee_form($form, &$form_state) {
  $form['name'] = array(
    '#title' => t('Name'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Name of the employee'),
  );
  $form['email'] = array(
    '#title' => t('Email'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Employee email'),
  );
  $form['department'] = array(
    '#title' => t('Department Name'),
    '#type' => 'textfield',
    '#description' => t('Department name'),
  );
   /*$form['pic'] = array(
        '#type' => 'file',
        '#title' => t('Upload an image'),
    );*/
    
    $form['pic'] = array(
  '#type' => 'managed_file',
  '#title' => t('Upload an image'),
  '#description' => t('Allowed extensions: gif png jpg jpeg'),
  '#upload_validators' => array(
    'file_validate_extensions' => array('gif png jpg jpeg'),
    // Pass the maximum file size in bytes
    'file_validate_size' => array(1 * 1024 * 1024),
  ),
  '#theme' => 'employee_thumb_upload',
  '#upload_location' => 'public://society/',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

function employee_theme($existing, $type, $theme, $path) {
	return array(
    'employee_thumb_upload' => array(
        'render element' => 'element',
        'file'           => 'employee.module',
));
}

function theme_employee_thumb_upload($variables) {

    $element = $variables['element'];
	//drupal_set_message('i am here');
    if (isset($element['#file']->uri)) {
        $output = '<div id="edit-logo-ajax-wrapper"><div class="form-item form-type-managed-file form-item-logo"><span class="file">';
        $output .= '<img height="50px" src="' . file_create_url($element['#file']->uri) . '" />';
        $output .= '</span><input type="submit" id="edit-' . $element['#name'] . '-remove-button" name="' . $element['#name'] . '_remove_button" value="Remove" class="form-submit ajax-processed">';
        $output .= '<input type="hidden" name="' . $element['#name'] . '[fid]" value="' . $element['#file']->fid . '">';

        return $output;
    }
}

function employee_form_submit($form, &$form_state) {
	/*variable_set('name', $form_state['values']['name']);
	drupal_set_message('Name is '.variable_get('name'));
	$nid = db_insert('employee')
  ->fields(array(
    'name' => $form_state['values']['name'],
    'email' => $form_state['values']['email'],
    'department' => $form_state['values']['department'],
    'image' => $form_state['values']['pic'],
  ))
  ->execute();*/
  
   $file = file_save_upload('pic', array(
		'file_validate_is_image' => array(), // Validates file is really an image.
		'file_validate_extensions' => array('png gif jpg jpeg'), // Validate extensions.
		)); 

 	// If the file passed validation:
	//if ($file) {
	variable_set('name', $form_state['values']['name']);
	drupal_set_message('Name is '.variable_get('name'));
	$nid = db_insert('employee')
  ->fields(array(
    'name' => $form_state['values']['name'],
    'email' => $form_state['values']['email'],
    'department' => $form_state['values']['department'],
    'image' => serialize($form_state['values']['pic']),
  ))
  ->execute();
	//}
	//else {
	//	form_set_error('file', t('No file was uploaded.'));
	//}
	//} 
    
}

/**
 * Menu callback.
 */
function employee_page() {
  return drupal_get_form('employee_form');
}